version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "01:00"
    open-pull-requests-limit: 99
    reviewers:
      - lipis
    assignees:
      - lipis
    labels:
      - "type: chore \U0001F9F9"

  - package-ecosystem: npm
    directory: "/src/packages/excalidraw/"
    schedule:
      interval: weekly
      day: sunday
      time: "01:00"
    open-pull-requests-limit: 99
    reviewers:
      - lipis
    assignees:
      - lipis
    labels:
      - "type: chore \U0001F9F9"
