name: Changelog in sync for packages

on:
  push:
  pull_request:
    branches-ignore:
      - l10n_master
      - dependabot/*
      - chenagelog # just testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install and run changelog check
        run: |
          npm ci
          npm run changelog:check
        env:
          CI: true
