name: Build locales percentages

on:
  push:
    paths:
      - "src/locales/**.json"
      - "!src/locales/percentages.json"

jobs:
  locales:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Create report file
        run: |
          npm run locales-coverage
          FILE_CHANGED=$(git diff --exit-code src/locales/percentages.json)
          if [ -z "${FILE_CHANGED}" ]; then
            git config --global user.name 'i18n automation'
            git add src/locales/percentages.json
            git commit -am "Calculate percentages of each translation file"
            git push
          fi
