name: Build locales coverage

on:
  push:
    branches:
      - "l10n_master"

jobs:
  locales:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TRANSLATIONS_COVERAGE_PAT }}

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Create report file
        run: |
          npm run locales-coverage
          FILE_CHANGED=$(git diff src/locales/percentages.json)
          if [ ! -z "${FILE_CHANGED}" ]; then
            git config --global user.name 'Kostas Bariotis'
            git config --global user.email 'konmpar@gmail.com'
            git add src/locales/percentages.json
            git commit -am "Auto commit: Calculate translation coverage"
            git push
          fi

      - name: Construct comment body
        id: getCommentBody
        run: |
          body=$(npm run locales-coverage:comment)
          comment_body="${comment_body//'%'/'%25'}"
          comment_body="${comment_body//$'\n'/'%0A'}"
          comment_body="${comment_body//$'\r'/'%0D'}"
          echo ::set-output name=body::$comment_body

      - name: update-pull-request
        uses: kt3k/update-pr-description@v1.0.1
        with:
          pr_body: ${{ steps.getCommentBody.outputs.body }}
          github-token: ${{ secrets.PUSH_TRANSLATIONS_COVERAGE_PAT }}
