name: Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Install and test
        run: |
          yarn --frozen-lockfile
          yarn test:app
